config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  devise_for :users
  resources :availableappts

  resources :notes

  resources :advisors

  resources :students

  resources :appointments

  resources :advisors do
    resources :appointments
  end

  resources :requiredcourses

  resources :courseplans do
    resources :requiredcourses
  end

  resources :courses

  resources :students do
    resources :appointments
    resources :notes
    resources :courses
    resources :courseplans
    resources :advisors
  end

  root 'welcome#index'

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :student
  validates_presence_of :student_id
  validates_presence_of :advisor_id
  validates_presence_of :message
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:note_id, :student_id, :advisor_id, :message)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :note_id %><br>
    <%= f.number_field :note_id %>
  </div>
  <div class="field">
    <%= f.label :student_id %><br>
    <%= f.number_field :student_id %>
  </div>
  <div class="field">
    <%= f.label :advisor_id %><br>
    <%= f.number_field :advisor_id %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<h1>Listing notes</h1>

<table>
  <thead>
    <tr>
      <th>Note</th>
      <th>Student</th>
      <th>Advisor</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.note_id %></td>
        <td><%= note.student_id %></td>
        <td><%= note.advisor_id %></td>
        <td><%= note.message %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Note:</strong>
  <%= @note.note_id %>
</p>

<p>
  <strong>Student:</strong>
  <%= @note.student_id %>
</p>

<p>
  <strong>Advisor:</strong>
  <%= @note.advisor_id %>
</p>

<p>
  <strong>Message:</strong>
  <%= @note.message %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>