matthew/AdvisementApp2/config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  devise_for :users
  resources :availableappts

  resources :notes

  resources :advisors

  resources :students

  resources :appointments

  resources :advisors do
    resources :appointments
  end

  resources :requiredcourses

  resources :courseplans do
    resources :requiredcourses
  end

  resources :courses

  resources :students do
    resources :appointments
    resources :notes
    resources :courses
    resources :courseplans
    resources :advisors
  end

  root 'welcome#index'

end

matthew/AdvisementApp2/app/models/advisor.rb
class Advisor < ActiveRecord::Base
  has_many :students
  has_many :appointments, dependent: :destroy
  has_many :availableappts, dependent: :destroy
end

matthew/AdvisementApp2/app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :student
  belongs_to :advisor
  #validates_presence_of :appointment_id
  validates_presence_of :appointment_date
  validates_presence_of :student_id
  validates_presence_of :advisor_id
  validates_presence_of :notes
end

matthew/AdvisementApp2/app/models/availableappt.rb
class Availableappt < ActiveRecord::Base
  belongs_to :advisor
  validates_presence_of :advisor_id
  validates_presence_of :date
end

matthew/AdvisementApp2/app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :student
  validates_presence_of :student_id
  validates_presence_of :name
  validates_presence_of :code
  validates_presence_of :credit_hours
  validates_presence_of :grade
end

matthew/AdvisementApp2/app/models/courseplan.rb
class Courseplan < ActiveRecord::Base
  belongs_to :student
  has_many :requiredcourses
  #validates_presence_of :student_id
  validates_presence_of :name
  validates_presence_of :department
  validates_presence_of :degree
  validates_presence_of :academic_year
end

matthew/AdvisementApp2/app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :student
  validates_presence_of :student_id
  validates_presence_of :advisor_id
  validates_presence_of :message
end

matthew/AdvisementApp2/app/models/requiredcourse.rb
class Requiredcourse < ActiveRecord::Base
  belongs_to :courseplan
  validates_presence_of :courseplan_id
  validates_presence_of :name
  validates_presence_of :code
  validates_presence_of :required_grade
  #validates_presence_of :description
end

matthew/AdvisementApp2/app/models/student.rb
class Student < ActiveRecord::Base
  has_many :courses, dependent: :destroy
  has_many :notes, dependent: :destroy
  has_many :appointments, dependent: :destroy
  has_one :courseplan
  belongs_to :advisor
  validates_presence_of :name
  validates_presence_of :lobo_id
  validates_presence_of :advisor_id
end

matthew/AdvisementApp2/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

matthew/AdvisementApp2/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:course_id, :student_id, :name, :code, :credit_hours, :grade)
    end
end

matthew/AdvisementApp2/app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:note_id, :student_id, :advisor_id, :message)
    end
end

matthew/AdvisementApp2/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

matthew/AdvisementApp2/app/helpers/advisors_helper.rb
module AdvisorsHelper
end

matthew/AdvisementApp2/app/helpers/application_helper.rb
module ApplicationHelper
end

matthew/AdvisementApp2/app/helpers/appointments_helper.rb
module AppointmentsHelper
end

matthew/AdvisementApp2/app/helpers/availableappts_helper.rb
module AvailableapptsHelper
end

matthew/AdvisementApp2/app/helpers/courseplans_helper.rb
module CourseplansHelper
end

matthew/AdvisementApp2/app/helpers/courses_helper.rb
module CoursesHelper
end

matthew/AdvisementApp2/app/helpers/notes_helper.rb
module NotesHelper
end

matthew/AdvisementApp2/app/helpers/requiredcourses_helper.rb
module RequiredcoursesHelper
end

matthew/AdvisementApp2/app/helpers/students_helper.rb
module StudentsHelper
end

matthew/AdvisementApp2/app/helpers/welcome_helper.rb
module WelcomeHelper
end

matthew/AdvisementApp2/app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :course_id %><br>
    <%= f.number_field :course_id %>
  </div>
  <div class="field">
    <%= f.label :student_id %><br>
    <%= f.number_field :student_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :credit_hours %><br>
    <%= f.text_field :credit_hours %>
  </div>
  <div class="field">
    <%= f.label :grade %><br>
    <%= f.text_field :grade %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

matthew/AdvisementApp2/app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

matthew/AdvisementApp2/app/views/courses/index.html.erb
<h1>Listing courses</h1>

<table>
  <thead>
    <tr>
      <th>Course</th>
      <th>Student</th>
      <th>Name</th>
      <th>Code</th>
      <th>Credit hours</th>
      <th>Grade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.course_id %></td>
        <td><%= course.student_id %></td>
        <td><%= course.name %></td>
        <td><%= course.code %></td>
        <td><%= course.credit_hours %></td>
        <td><%= course.grade %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

matthew/AdvisementApp2/app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

matthew/AdvisementApp2/app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Course:</strong>
  <%= @course.course_id %>
</p>

<p>
  <strong>Student:</strong>
  <%= @course.student_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @course.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @course.code %>
</p>

<p>
  <strong>Credit hours:</strong>
  <%= @course.credit_hours %>
</p>

<p>
  <strong>Grade:</strong>
  <%= @course.grade %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

matthew/AdvisementApp2/app/views/welcome/_navig.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <nav class="navbar navbar-default navbar-custom" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="http://www.unm.edu"><img src="http://degrees.unm.edu/assets/layout/Logo-072057a2d0687e68145f541da12b18e3.png">
          </a>
        </div>

        <p class="navbar-text pull-right">
          <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li class="active"><a href="http://localhost:3000/welcome/index"> LoboAchieve</a></li>
              <li class="active"><a href="http://localhost:3000/students/1"> My Page</a></li>

            </ul>

          </li>
        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </nav>
  </div>
</div>
</div>

matthew/AdvisementApp2/app/views/welcome/index.html.erb
<%= render 'navig' %>

<div class="center jumbotron">
  <h1>Lobo Achieve</h1>

  <h2>
    Web Advisement Application
  </h2>

  <%= link_to "Log-in", 'users/sign_in', class: "btn btn-lg btn-primary" %>
</div>