AdvisementApp3/config/routes.rb
Rails.application.routes.draw do
  resources :studentcourses

  resources :courseplancourses

  resources :courses

  resources :courseplans do
    resources :courses
  end

  resources :notes

  resources :appointments

  resources :advisors

  resources :students do
    resources :courseplans
  end

end

AdvisementApp3/app/controllers/studentcourses_controller.rb
class StudentcoursesController < ApplicationController
  before_action :set_studentcourse, only: [:show, :edit, :update, :destroy]

  # GET /studentcourses
  # GET /studentcourses.json
  def index
    @studentcourses = Studentcourse.all
  end

  # GET /studentcourses/1
  # GET /studentcourses/1.json
  def show
  end

  # GET /studentcourses/new
  def new
    @studentcourse = Studentcourse.new
  end

  # GET /studentcourses/1/edit
  def edit
  end

  # POST /studentcourses
  # POST /studentcourses.json
  def create
    @studentcourse = Studentcourse.new(studentcourse_params)

    respond_to do |format|
      if @studentcourse.save
        format.html { redirect_to @studentcourse, notice: 'Studentcourse was successfully created.' }
        format.json { render :show, status: :created, location: @studentcourse }
      else
        format.html { render :new }
        format.json { render json: @studentcourse.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /studentcourses/1
  # PATCH/PUT /studentcourses/1.json
  def update
    respond_to do |format|
      if @studentcourse.update(studentcourse_params)
        format.html { redirect_to @studentcourse, notice: 'Studentcourse was successfully updated.' }
        format.json { render :show, status: :ok, location: @studentcourse }
      else
        format.html { render :edit }
        format.json { render json: @studentcourse.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /studentcourses/1
  # DELETE /studentcourses/1.json
  def destroy
    @studentcourse.destroy
    respond_to do |format|
      format.html { redirect_to studentcourses_url, notice: 'Studentcourse was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_studentcourse
      @studentcourse = Studentcourse.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def studentcourse_params
      params.require(:studentcourse).permit(:studentcourse_id, :student_id, :course_id, :received_grade, :date_completed)
    end
end

AdvisementApp3/app/helpers/studentcourses_helper.rb
module StudentcoursesHelper
end

AdvisementApp3/app/views/studentcourses/_form.html.erb
<%= form_for(@studentcourse) do |f| %>
  <% if @studentcourse.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@studentcourse.errors.count, "error") %> prohibited this studentcourse from being saved:</h2>

      <ul>
      <% @studentcourse.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :studentcourse_id %><br>
    <%= f.text_field :studentcourse_id %>
  </div>
  <div class="field">
    <%= f.label :student_id %><br>
    <%= f.number_field :student_id %>
  </div>
  <div class="field">
    <%= f.label :course_id %><br>
    <%= f.number_field :course_id %>
  </div>
  <div class="field">
    <%= f.label :received_grade %><br>
    <%= f.text_field :received_grade %>
  </div>
  <div class="field">
    <%= f.label :date_completed %><br>
    <%= f.text_field :date_completed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

AdvisementApp3/app/views/studentcourses/edit.html.erb
<h1>Editing studentcourse</h1>

<%= render 'form' %>

<%= link_to 'Show', @studentcourse %> |
<%= link_to 'Back', studentcourses_path %>

AdvisementApp3/app/views/studentcourses/index.html.erb
<h1>Listing studentcourses</h1>

<table>
  <thead>
    <tr>
      <th>Studentcourse</th>
      <th>Student</th>
      <th>Course</th>
      <th>Received grade</th>
      <th>Date completed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @studentcourses.each do |studentcourse| %>
      <tr>
        <td><%= studentcourse.studentcourse_id %></td>
        <td><%= studentcourse.student_id %></td>
        <td><%= studentcourse.course_id %></td>
        <td><%= studentcourse.received_grade %></td>
        <td><%= studentcourse.date_completed %></td>
        <td><%= link_to 'Show', studentcourse %></td>
        <td><%= link_to 'Edit', edit_studentcourse_path(studentcourse) %></td>
        <td><%= link_to 'Destroy', studentcourse, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Studentcourse', new_studentcourse_path %>

AdvisementApp3/app/views/studentcourses/new.html.erb
<h1>New studentcourse</h1>

<%= render 'form' %>

<%= link_to 'Back', studentcourses_path %>

AdvisementApp3/app/views/studentcourses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Studentcourse:</strong>
  <%= @studentcourse.studentcourse_id %>
</p>

<p>
  <strong>Student:</strong>
  <%= @studentcourse.student_id %>
</p>

<p>
  <strong>Course:</strong>
  <%= @studentcourse.course_id %>
</p>

<p>
  <strong>Received grade:</strong>
  <%= @studentcourse.received_grade %>
</p>

<p>
  <strong>Date completed:</strong>
  <%= @studentcourse.date_completed %>
</p>

<%= link_to 'Edit', edit_studentcourse_path(@studentcourse) %> |
<%= link_to 'Back', studentcourses_path %>