config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  devise_for :users
  resources :availableappts

  resources :notes

  resources :advisors

  resources :students

  resources :appointments

  resources :advisors do
    resources :appointments
  end

  resources :requiredcourses

  resources :courseplans do
    resources :requiredcourses
  end

  resources :courses

  resources :students do
    resources :appointments
    resources :notes
    resources :courses
    resources :courseplans
    resources :advisors
  end

  root 'welcome#index'

end

app/models/advisor.rb
class Advisor < ActiveRecord::Base
  has_many :students
  has_many :appointments, dependent: :destroy
  has_many :availableappts, dependent: :destroy
end

app/controllers/advisors_controller.rb
class AdvisorsController < ApplicationController
  before_action :set_advisor, only: [:show, :edit, :update, :destroy]

  # GET /advisors
  # GET /advisors.json
  def index
    @advisors = Advisor.all
  end

  # GET /advisors/1
  # GET /advisors/1.json
  def show
  end

  # GET /advisors/new
  def new
    @advisor = Advisor.new
    @all_advisors = Advisor.all
  end

  # GET /advisors/1/edit
  def edit
  end

  # POST /advisors
  # POST /advisors.json
  def create
    @advisor = Advisor.new(advisor_params)

    respond_to do |format|
      if @advisor.save
        format.html { redirect_to @advisor, notice: 'Advisor was successfully created.' }
        format.json { render :show, status: :created, location: @advisor }
      else
        format.html { render :new }
        format.json { render json: @advisor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /advisors/1
  # PATCH/PUT /advisors/1.json
  def update
    respond_to do |format|
      if @advisor.update(advisor_params)
        format.html { redirect_to @advisor, notice: 'Advisor was successfully updated.' }
        format.json { render :show, status: :ok, location: @advisor }
      else
        format.html { render :edit }
        format.json { render json: @advisor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advisors/1
  # DELETE /advisors/1.json
  def destroy
    @advisor.destroy
    respond_to do |format|
      format.html { redirect_to advisors_url, notice: 'Advisor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advisor
      @advisor = Advisor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advisor_params
      params.require(:advisor).permit(:advisor_id, :name, :department, :office_location, :email, :phone)
    end
end

app/helpers/advisors_helper.rb
module AdvisorsHelper
end

app/views/advisors/_form.html.erb
<%= form_for(@advisor) do |f| %>
  <% if @advisor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@advisor.errors.count, "error") %> prohibited this advisor from being saved:</h2>

      <ul>
      <% @advisor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :department %><br>
    <%= f.text_field :department %>
  </div>
  <div class="field">
    <%= f.label :office_location %><br>
    <%= f.text_field :office_location %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/advisors/_navig.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <nav class="navbar navbar-default navbar-custom" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="http://www.unm.edu"><img src="http://degrees.unm.edu/assets/layout/Logo-072057a2d0687e68145f541da12b18e3.png">
          </a>
        </div>

        <p class="navbar-text pull-right">
          <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li class="active"><a href="http://localhost:3000/welcome/index"> LoboAchieve</a></li>
              <li class="active"><a href="http://localhost:3000/students/1"> My Page</a></li>

            </ul>

          </li>
        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </nav>
  </div>
</div>
</div>

app/views/advisors/edit.html.erb
<h1>Editing advisor</h1>

<%= form_for(@advisor) do |f| %>
  <% if @advisor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@advisor.errors.count, "error") %> prohibited this advisor from being saved:</h2>

      <ul>
      <% @advisor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :department %><br>
    <%= f.text_field :department %>
  </div>
  <div class="field">
    <%= f.label :office_location %><br>
    <%= f.text_field :office_location %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Show', @advisor %> |
<%= link_to 'Back', advisors_path %>

app/views/advisors/index.html.erb
<h1>Listing advisors</h1>

<table>
  <thead>
    <tr>
      <th>Advisor</th>
      <th>Name</th>
      <th>Department</th>
      <th>Office location</th>
      <th>Email</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @advisors.each do |advisor| %>
      <tr>
        <td><%= advisor.advisor_id %></td>
        <td><%= advisor.name %></td>
        <td><%= advisor.department %></td>
        <td><%= advisor.office_location %></td>
        <td><%= advisor.email %></td>
        <td><%= advisor.phone %></td>
        <td><%= link_to 'Show', advisor %></td>
        <td><%= link_to 'Edit', edit_advisor_path(advisor) %></td>
        <td><%= link_to 'Destroy', advisor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Advisor', new_advisor_path %>

app/views/advisors/new.html.erb
<h1>New advisor</h1>

<%= form_for(@advisor) do |f| %>
  <% if @advisor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@advisor.errors.count, "error") %> prohibited this advisor from being saved:</h2>

      <ul>
      <% @advisor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :advisor_id, :value => @all_advisors.size + 1 %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :department %><br>
    <%= f.text_field :department %>
  </div>
  <div class="field">
    <%= f.label :office_location %><br>
    <%= f.text_field :office_location %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', advisors_path %>

app/views/advisors/show.html.erb
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US" xmlns:xhtml="http://www.w3.org/1999/xhtml" lang="en-US"><head>
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
  <title>index ::
    LoboAchieve Info | The University of New Mexico</title>

    <head>
      <div id="header">
        <%= render 'navig' %>
        <br><br>
      </div>
    </head>



    <body>
      <div id="page">

        <div id="advisorinfo" class="well well-lg">
          <div style="float: left; width: 310px;">
            <p>
              <strong>Name:</strong>
              <%= @advisor.name %>
            </p>
            <p>
              <strong>Department:</strong>
              <%= @advisor.department %>
            </p>
            <p>
              <strong>Office location:</strong>
              <%= @advisor.office_location %>
            </p>
            <p>
              <strong>Email:</strong>
              <%= @advisor.email %>
            </p>
            <p>
              <strong>Phone:</strong>
              <%= @advisor.phone %>
            </p>
          </div>
          <div style="float: left; width: 460px;">
            <p>
              <strong>Email:</strong>
              <%= @advisor.email %>
            </p>
            <p>
              <strong>Phone:</strong>
              <%= @advisor.phone %>
            </p>
          </div>
          <div style="float: left;">
            <img src="http://www.theboxingobserver.com/wp-content/uploads/2013/07/Rocky-Apollo-Creed-Grandson-Stallone.jpg" width="140px" height="100px" class="rotate90">
          </div>
          <br style="clear: left;" />
        </div>


        <div id="advisor_appts" class="well well-lg" style="float: left;">
          <div id="content">
            <ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
              <li class="active"><a href="#advisor" data-toggle="tab">My Available Appts</a></li>
              <li><a href="#appts" data-toggle="tab">Create Available Appts</a></li>
              <li><a href="#upcoming" data-toggle="tab">Upcoming Appts</a></li>
            </ul>
            <div id="my-tab-content" class="tab-content">
              <div class="tab-pane active" id="advisor"></br>
                <div id="advisor">
                <% @advisor.availableappts.each do |appt| %>
                <%= div_for appt do %>
                <p>
                  <strong> <%= appt.date %></strong> <br/>
                  <p>
                    <% end %>
                    <% end %>
                  </div>
                </div>

                <div class="tab-pane" id="appts"><br/>

                  <%= form_for([Availableappt.new]) do |f| %>
                  <p>
                    <%= f.label :body, "Date and Time:" %><br />
                    <%= f.datetime_select :date %><br />
                    <%= f.hidden_field :advisor_id, :value => @advisor.advisor_id %>
                    <%@appts = Availableappt.all%>
                    <%= f.hidden_field :appt_id, :value => @appts.size + 1 %>
                  </p>

                  <p><%= f.submit "Create Available Appointment" %></p>
                  <% end %>

                </form>
              </div>

              <div class="tab-pane" id="upcoming"></br>
                <% @advisor.appointments.each do |appt| %>
                <%= div_for appt do %>
                <p>
                  <%@student = Student.find(appt.student_id)%>
                  <strong> Student: <%= @student.name %></strong> <br/>
                  <%= h(appt.appointment_date) %> <br/>
                  <%= h(appt.notes) %>
                  <p>
                    <% end %>
                    <% end %>
                    </div>

            </div>
            </div>
          </div>

          <div id="advisor_notes" class="well well-lg" style="float: right;">
            <strong>Notes</strong>
            <div id="notes">
              <%@my_students = Array.new %>
              <% @advisor.students.each do |s| %>
              <%= div_for s do %>
              <%@my_students.push(s)%>
              <% end %>
              <% end %>

              <%= form_for([Note.new]) do |f| %>
              <p>
                <% @student_options = @my_students.map{|s| [ s.name, s.student_id ] }%>
                <%= f.select( :student_id, @student_options)%>
                <%= f.hidden_field :advisor_id, :value => @advisor.advisor_id %>
                <%= f.text_area :message %>
              </p>

              <p><%= f.submit "Add Note" %></p>
              <% end %>
            </div>


          </form>
        </div>
      </div>